FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
RUN npm run prisma:generate

COPY . .
RUN npm run build

EXPOSE 4001

CMD ["sh", "-c", "npx prisma migrate deploy && node dist/main"]
